name: Continuous Integration
permissions: read-all

on:
  pull_request:
    branches:
      - main

concurrency:
  # yamllint disable-line rule:line-length
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Download actionlint
        id: get_actionlint
        # yamllint disable-line rule:line-length
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.6.15

      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color

  lint:
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4.1.1

      - name: Setup Node 🔧
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20

      - name: Lint
        run: |
          npm ci
          npm run check

  docs:
    timeout-minutes: 20
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4.1.1

      - name: Setup Node 🔧
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build 🔧
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        # `@rollup/rollup-linux-x64-gnu` is not installed when running npm ci, we have to install it manually
        run: |
          npm ci
          npm i @rollup/rollup-linux-x64-gnu
          npm run build

      # NOTE(sileht): workflow run on/pull_request doesn't have access to
      # secrets
      # So, we upload it as artifact, then another workflow
      # docs-upload-gcp-temp.yaml will upload it on gcp.
      - name: Upload ☁️
        uses: actions/upload-artifact@v4
        with:
          name: docs-pr-${{ github.event.pull_request.number }}
          path: dist

      # yamllint disable-line rule:line-length
      - run: echo "docs=https://docs-preview.mergify.com/${{ github.event.pull_request.number }}/docs" >> "$GITHUB_OUTPUT"
        shell: bash
